default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/identity_provider_development

test:
  <<: *default
  database: db/identity_provider_test

production:
  <<: *default
  database: db/identity_provider_production
